export const DUMMY_ITEMS = [
  {
    productId: 'prod-001',
    productTitle: 'Apple iPhone 14',
    productImage: 'https://via.placeholder.com/150',
    productDescription: 'The latest Apple iPhone with A15 Bionic chip.',
    productPrice: 999,
    productRating: 4.8,
    productCategory: 'Electronics',
    estimatedDelivery: '2-3 days',
  },
  {
    productId: 'prod-002',
    productTitle: 'Samsung Galaxy S22',
    productImage: 'https://via.placeholder.com/150',
    productDescription: 'High-end Samsung phone with an excellent camera.',
    productPrice: 899,
    productRating: 4.5,
    productCategory: 'Electronics',
    estimatedDelivery: '3-4 days',
  },
  {
    productId: 'prod-003',
    productTitle: 'Sony WH-1000XM5',
    productImage: 'https://via.placeholder.com/150',
    productDescription: 'Top-notch noise-canceling headphones from Sony.',
    productPrice: 349,
    productRating: 4.7,
    productCategory: 'Electronics',
    estimatedDelivery: '1-2 days',
  },
  {
    productId: 'prod-004',
    productTitle: 'Dell XPS 13',
    productImage: 'https://via.placeholder.com/150',
    productDescription: 'Premium ultrabook with Intel Core i7 processor.',
    productPrice: 1199,
    productRating: 4.6,
    productCategory: 'Electronics',
    estimatedDelivery: '5-7 days',
  },
  {
    productId: 'prod-005',
    productTitle: 'Nike Air Max 270',
    productImage: 'https://via.placeholder.com/150',
    productDescription: 'Stylish and comfortable running shoes by Nike.',
    productPrice: 150,
    productRating: 4.4,
    productCategory: 'Fashion',
    estimatedDelivery: '3-5 days',
  },
  {
    productId: 'prod-006',
    productTitle: 'Adidas Ultraboost 21',
    productImage: 'https://via.placeholder.com/150',
    productDescription: 'High-performance running shoes by Adidas.',
    productPrice: 180,
    productRating: 4.5,
    productCategory: 'Fashion',
    estimatedDelivery: '2-3 days',
  },
  {
    productId: 'prod-007',
    productTitle: 'Apple MacBook Pro 16"',
    productImage: 'https://via.placeholder.com/150',
    productDescription: 'Powerful laptop with M1 Pro chip by Apple.',
    productPrice: 2499,
    productRating: 4.9,
    productCategory: 'Electronics',
    estimatedDelivery: '4-6 days',
  },
  {
    productId: 'prod-008',
    productTitle: 'Sony PlayStation 5',
    productImage: 'https://via.placeholder.com/150',
    productDescription: 'Next-gen gaming console from Sony.',
    productPrice: 499,
    productRating: 4.8,
    productCategory: 'Gaming',
    estimatedDelivery: '7-10 days',
  },
  {
    productId: 'prod-009',
    productTitle: 'Microsoft Xbox Series X',
    productImage: 'https://via.placeholder.com/150',
    productDescription: 'Powerful gaming console by Microsoft.',
    productPrice: 499,
    productRating: 4.7,
    productCategory: 'Gaming',
    estimatedDelivery: '5-7 days',
  },
  {
    productId: 'prod-010',
    productTitle: 'GoPro HERO10',
    productImage: 'https://via.placeholder.com/150',
    productDescription: 'Latest action camera from GoPro with 5.3K video.',
    productPrice: 399,
    productRating: 4.6,
    productCategory: 'Electronics',
    estimatedDelivery: '2-4 days',
  },
  {
    productId: 'prod-011',
    productTitle: 'Fitbit Charge 5',
    productImage: 'https://via.placeholder.com/150',
    productDescription: 'Advanced fitness and health tracker by Fitbit.',
    productPrice: 179,
    productRating: 4.3,
    productCategory: 'Wearables',
    estimatedDelivery: '3-5 days',
  },
  {
    productId: 'prod-012',
    productTitle: 'Canon EOS R5',
    productImage: 'https://via.placeholder.com/150',
    productDescription: 'High-resolution mirrorless camera from Canon.',
    productPrice: 3899,
    productRating: 4.9,
    productCategory: 'Cameras',
    estimatedDelivery: '4-6 days',
  },
  {
    productId: 'prod-013',
    productTitle: 'DJI Mavic Air 2',
    productImage: 'https://via.placeholder.com/150',
    productDescription: 'Compact and powerful drone by DJI.',
    productPrice: 799,
    productRating: 4.7,
    productCategory: 'Drones',
    estimatedDelivery: '3-5 days',
  },
  {
    productId: 'prod-014',
    productTitle: 'Kindle Paperwhite',
    productImage: 'https://via.placeholder.com/150',
    productDescription: 'Waterproof e-reader with high-resolution display.',
    productPrice: 129,
    productRating: 4.6,
    productCategory: 'Electronics',
    estimatedDelivery: '1-3 days',
  },
  {
    productId: 'prod-015',
    productTitle: 'Nikon Z6 II',
    productImage: 'https://via.placeholder.com/150',
    productDescription: 'Full-frame mirrorless camera from Nikon.',
    productPrice: 1999,
    productRating: 4.5,
    productCategory: 'Cameras',
    estimatedDelivery: '5-7 days',
  },
  {
    productId: 'prod-016',
    productTitle: 'Apple Watch Series 8',
    productImage: 'https://via.placeholder.com/150',
    productDescription: 'Advanced smartwatch with health features.',
    productPrice: 399,
    productRating: 4.7,
    productCategory: 'Wearables',
    estimatedDelivery: '2-3 days',
  },
  {
    productId: 'prod-017',
    productTitle: 'Samsung Galaxy Watch 5',
    productImage: 'https://via.placeholder.com/150',
    productDescription: 'Smartwatch with advanced fitness tracking.',
    productPrice: 279,
    productRating: 4.4,
    productCategory: 'Wearables',
    estimatedDelivery: '3-4 days',
  },
  {
    productId: 'prod-018',
    productTitle: 'Logitech MX Master 3',
    productImage: 'https://via.placeholder.com/150',
    productDescription: 'High-precision ergonomic mouse by Logitech.',
    productPrice: 99,
    productRating: 4.8,
    productCategory: 'Accessories',
    estimatedDelivery: '1-2 days',
  },
  {
    productId: 'prod-019',
    productTitle: 'Razer BlackWidow V3',
    productImage: 'https://via.placeholder.com/150',
    productDescription: 'High-performance mechanical gaming keyboard.',
    productPrice: 139,
    productRating: 4.5,
    productCategory: 'Gaming Accessories',
    estimatedDelivery: '2-3 days',
  },
  {
    productId: 'prod-020',
    productTitle: 'Bose QuietComfort 45',
    productImage: 'https://via.placeholder.com/150',
    productDescription: 'Industry-leading noise-canceling headphones by Bose.',
    productPrice: 329,
    productRating: 4.7,
    productCategory: 'Electronics',
    estimatedDelivery: '2-4 days',
  },
]
